### ISSUE TITLE
Unclear syntax for the TOSCA template

### ISSUE THREAD

**Issue by iblanque** [indigo-dc/orchent#3]
Hi,

I am trying to intantitate a TOSCA template with orchent. The template works when I use directly the REST API through POSTMAN. However, I get syntax errors which are unclear.

Can you add a working example in the documentation?

My template is:
```
{
imports:
  - indigo_custom_types: https://raw.githubusercontent.com/indigo-dc/tosca-types/master/custom_types.yaml

description: >
  TOSCA template for deploying EUBIOSTEO app.

topology_template:

  inputs:
    number_cpus:
      type: integer
      description: number of cpus required for the instance
      default: 1
    memory_size:
      type: string
      description: ram memory required for the instance
      default: 1 GB

  node_templates:
    eubiosteo:
      type: tosca.nodes.indigo.Eubiosteo
      requirements:
        - host: eubiosteo_server

    eubiosteo_server:
      type: tosca.nodes.indigo.Compute
      capabilities:
        endpoint:
          properties:
            network_name: PUBLIC
            ports:
              http_port:
                protocol: tcp
                source: 22
        # Host container properties
        host:
         properties:
           num_cpus: { get_input: number_cpus }
           mem_size: { get_input: memory_size }
        # Guest Operating System properties
        os:
          properties:
            # host Operating System image properties
            type: linux
            distribution: centos
            version: 7
            image: indigodatacloudapps/eubiosteo

  outputs:
    instance_ip:
      value: { get_attribute: [ eubiosteo_server, public_address, 0 ] }
    instance_creds:
      value: { get_attribute: [ eubiosteo_server, endpoint, credential, 0 ] }
}
```

My errors are the following:

> ./orchent -u http://orchestrator01-indigo.cloud.ba.infn.it:8080/orchestrator depcreate template.txt '{ "number_cpus" : 1,   "memory_size" : "512 MB" }' 
> error creating deployment:
>  Error 'Bad Request' [400]: Template is invalid: Context: while parsing a flow node
> Problem: expected the node content, but found BlockEntry
> Note: null
> Start: SimpleMark(line=3, column=3)
> End  : SimpleMark(line=3, column=3)
> Level: ERROR
> Code : INVALID_YAML; 

Many thanks!

**Comment by bwegh** [comment]
hello,
thanks for reporting the issue, I will give it a try myself, I do not see an issue with your call.

regarding the example: https://indigo-dc.gitbooks.io/orchent/content/user.html (which does not include a template file)

**Comment by bwegh** [comment]
your issue are the curly braces, which are not part of a yml file and a missing version.
it works by just removing the first and last line and adding a tosca version:
```
tosca_definitions_version: tosca_simple_yaml_1_0

imports:
  - indigo_custom_types: https://raw.githubusercontent.com/indigo-dc/tosca-types/master/custom_types.yaml

description: >
  TOSCA template for deploying EUBIOSTEO app.

topology_template:

  inputs:
    number_cpus:
      type: integer
      description: number of cpus required for the instance
      default: 1
    memory_size:
      type: string
      description: ram memory required for the instance
      default: 1 GB

  node_templates:
    eubiosteo:
      type: tosca.nodes.indigo.Eubiosteo
      requirements:
        - host: eubiosteo_server

    eubiosteo_server:
      type: tosca.nodes.indigo.Compute
      capabilities:
        endpoint:
          properties:
            network_name: PUBLIC
            ports:
              http_port:
                protocol: tcp
                source: 22
        # Host container properties
        host:
         properties:
           num_cpus: { get_input: number_cpus }
           mem_size: { get_input: memory_size }
        # Guest Operating System properties
        os:
          properties:
            # host Operating System image properties
            type: linux
            distribution: centos
            version: 7
            image: indigodatacloudapps/eubiosteo

  outputs:
    instance_ip:
      value: { get_attribute: [ eubiosteo_server, public_address, 0 ] }
    instance_creds:
      value: { get_attribute: [ eubiosteo_server, endpoint, credential, 0 ] }
```

in general regarding templates please ask the orchestrator team, as the client is just passing the template file to the orchestrator without changing it.
